[   INFO] [2018-04-18 15:56:46,769] [51404] [HTMLReport.py(95)] - The number of concurrent threads is expected to be 5
[   INFO] [2018-04-18 15:56:46,770] [39912] [Result.py(45)] - Start Test: test_error (__main__.test_1th)
[  ERROR] [2018-04-18 15:56:46,770] [39912] [HTMLReport_test.py(35)] - 测试错误
[   INFO] [2018-04-18 15:56:46,770] [53056] [Result.py(45)] - Start Test: test_fail (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,771] [29732] [Result.py(45)] - Start Test: test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,771] [53056] [HTMLReport_test.py(45)] - 测试失败
[   INFO] [2018-04-18 15:56:46,771] [41792] [Result.py(45)] - Start Test: test_skip (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,771] [29732] [HTMLReport_test.py(20)] - 测试isupper
[   INFO] [2018-04-18 15:56:46,773] [45136] [Result.py(45)] - Start Test: test_split (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,773] [41792] [Result.py(78)] - Skip Test: test_skip (__main__.test_1th)
这是一个跳过的测试
[WARNING] [2018-04-18 15:56:46,773] [53056] [Result.py(127)] - Failure: test_fail (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 46, in test_fail
    self.assertEqual(1, 2, "相等")
AssertionError: 1 != 2 : 相等

[   INFO] [2018-04-18 15:56:46,774] [29732] [HTMLReport_test.py(21)] - 11111111111111111111111111111111111111111111111111111
[   INFO] [2018-04-18 15:56:46,774] [45136] [HTMLReport_test.py(27)] - 测试split
[   INFO] [2018-04-18 15:56:46,775] [41792] [Result.py(56)] - Stop Test: test_skip (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,775] [53056] [Result.py(56)] - Stop Test: test_fail (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,775] [29732] [Result.py(93)] - Pass Test: test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,775] [45136] [Result.py(93)] - Pass Test: test_split (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,776] [41792] [Result.py(58)] - Duration: 0.0017383615685624553
[   INFO] [2018-04-18 15:56:46,776] [53056] [Result.py(58)] - Duration: 0.004170471193680012
[   INFO] [2018-04-18 15:56:46,776] [29732] [Result.py(56)] - Stop Test: test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,776] [45136] [Result.py(56)] - Stop Test: test_split (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,777] [29732] [Result.py(58)] - Duration: 0.004614469949875277
[   INFO] [2018-04-18 15:56:46,777] [45136] [Result.py(58)] - Duration: 0.001790820325715663
[  ERROR] [2018-04-18 15:56:46,783] [39912] [Result.py(110)] - Error Test: test_error (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 41, in test_error
    raise ValueError
ValueError

[   INFO] [2018-04-18 15:56:46,783] [39912] [Result.py(56)] - Stop Test: test_error (__main__.test_1th)
[   INFO] [2018-04-18 15:56:46,783] [39912] [Result.py(58)] - Duration: 0.012960734240134903
[   INFO] [2018-04-18 15:56:46,784] [52888] [Result.py(45)] - Start Test: test_bad_int (__main__.test_2th)
[   INFO] [2018-04-18 15:56:46,784] [52888] [HTMLReport_test.py(58)] - 测试异常类型
[   INFO] [2018-04-18 15:56:46,784] [38036] [Result.py(45)] - Start Test: test_upper (__main__.test_2th)
[  ERROR] [2018-04-18 15:56:46,784] [52888] [Result.py(110)] - Error Test: test_bad_int (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 59, in test_bad_int
    self.assertRaises(ValueError, parse_int("1.5"), 'N/A')
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 11, in parse_int
    return int(s)
ValueError: invalid literal for int() with base 10: '1.5'

[   INFO] [2018-04-18 15:56:46,784] [52888] [Result.py(56)] - Stop Test: test_bad_int (__main__.test_2th)
[   INFO] [2018-04-18 15:56:46,784] [52888] [Result.py(58)] - Duration: 0.0008944598230543315
[CRITICAL] [2018-04-18 15:56:46,784] [38036] [HTMLReport_test.py(63)] - 测试相等
[WARNING] [2018-04-18 15:56:46,785] [38036] [Result.py(127)] - Failure: test_upper (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 64, in test_upper
    self.assertEqual('foo'.upper(), '00')
AssertionError: 'FOO' != '00'
- FOO
+ 00


[   INFO] [2018-04-18 15:56:46,785] [38036] [Result.py(56)] - Stop Test: test_upper (__main__.test_2th)
[   INFO] [2018-04-18 15:56:46,785] [38036] [Result.py(58)] - Duration: 0.0009834116286619437
[   INFO] [2018-04-18 15:56:46,786] [48136] [Result.py(45)] - Start Test: test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 15:56:46,786] [57676] [Result.py(45)] - Start Test: test_True (__main__.test_第三个测试)
[WARNING] [2018-04-18 15:56:46,786] [48136] [Result.py(127)] - Failure: test_False (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 83, in test_False
    self.assertFalse(True, self.a)
AssertionError: True is not false : 2

[   INFO] [2018-04-18 15:56:46,787] [48136] [Result.py(56)] - Stop Test: test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 15:56:46,787] [48136] [Result.py(58)] - Duration: 0.0007325219205379062
[WARNING] [2018-04-18 15:56:46,787] [57676] [Result.py(127)] - Failure: test_True (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 78, in test_True
    self.assertTrue(False, self.a)
AssertionError: False is not true : 3

[   INFO] [2018-04-18 15:56:46,787] [57676] [Result.py(56)] - Stop Test: test_True (__main__.test_第三个测试)
[   INFO] [2018-04-18 15:56:46,787] [57676] [Result.py(58)] - Duration: 0.0010328292984439526
[   INFO] [2018-04-18 15:56:46,788] [51404] [HTMLReport.py(123)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split

[  ERROR] [2018-04-18 15:56:46,788] [51404] [HTMLReport.py(125)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Error	test_error (__main__.test_1th)	测试错误
Error	test_bad_int (__main__.test_2th)	测试异常类型
Fail	test_upper (__main__.test_2th)	测试相等
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-04-18 15:56:46,805] [51404] [HTMLReport.py(143)] - 
EOT！
Ran 9 tests in 0:00:00.019464

PASS：2
Failures：4
Skipped：1
Errors：2
