[   INFO] [2018-03-14 17:17:02,241] [23268] [HTMLReport.py(92)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:17:02,243] [19204] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,243] [840] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-14 17:17:02,244] [19204] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:17:02,244] [13428] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,245] [840] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:17:02,245] [19948] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,246] [13428] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:17:02,247] [23244] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,249] [19948] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-14 17:17:02,250] [19204] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[WARNING] [2018-03-14 17:17:02,250] [840] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,250] [13428] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,251] [23244] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:17:02,251] [19948] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,251] [19204] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,252] [840] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,252] [13428] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,252] [23244] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,254] [23244] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,255] [24440] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,255] [6064] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,255] [24440] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:17:02,255] [6064] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,256] [24440] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,256] [6064] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,256] [24440] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,258] [20780] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,258] [23892] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:17:02,259] [20780] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:17:02,259] [23892] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,260] [20780] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,260] [23892] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,278] [23268] [HTMLReport.py(129)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_upper (__main__.test_2th)	测试相等
Pass	test_bad_int (__main__.test_2th)	测试异常类型

[  ERROR] [2018-03-14 17:17:02,278] [23268] [HTMLReport.py(131)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:17:02,278] [23268] [HTMLReport.py(132)] - 
测试结束！
运行时间: 0:00:00.019954
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-14 17:18:04,923] [23688] [HTMLReport.py(92)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:18:04,923] [12324] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,924] [21440] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-14 17:18:04,924] [12324] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:18:04,925] [1912] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,925] [21440] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:18:04,926] [18456] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,927] [18192] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,928] [1912] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:18:04,928] [18456] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[WARNING] [2018-03-14 17:18:04,929] [21440] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,929] [18192] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:18:04,930] [1912] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,930] [18456] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[  ERROR] [2018-03-14 17:18:04,930] [12324] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,931] [21440] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,931] [18192] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,931] [1912] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,932] [12324] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,933] [18192] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,933] [24168] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,934] [24168] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:18:04,934] [14664] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,934] [24168] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,935] [14664] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,935] [24168] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,936] [14664] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,937] [13860] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,938] [9096] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:18:04,938] [13860] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,938] [13860] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:18:04,938] [9096] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,938] [9096] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,957] [23688] [HTMLReport.py(129)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-14 17:18:04,958] [23688] [HTMLReport.py(131)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Error	test_error (__main__.test_1th)	测试错误
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:18:04,958] [23688] [HTMLReport.py(132)] - 
测试结束！
运行时间: 0:00:00.016652
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-14 17:25:45,825] [5668] [HTMLReport.py(94)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:25:45,826] [11120] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-14 17:25:45,827] [11120] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:25:45,827] [6004] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,829] [8412] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,830] [2564] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,830] [6004] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:25:45,830] [8412] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:25:45,830] [19548] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,831] [2564] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-14 17:25:45,832] [11120] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,832] [8412] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,833] [19548] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:25:45,833] [2564] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,834] [11120] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,835] [8412] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,835] [19548] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[WARNING] [2018-03-14 17:25:45,835] [6004] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,836] [19548] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,837] [6004] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,838] [23592] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,838] [23592] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:25:45,839] [18092] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,839] [23592] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,839] [18092] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,840] [23592] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,840] [18092] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,841] [23596] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,842] [23288] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:25:45,842] [23596] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,843] [23596] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:25:45,843] [23288] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,844] [23288] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,870] [5668] [HTMLReport.py(131)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-14 17:25:45,870] [5668] [HTMLReport.py(133)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:25:45,870] [5668] [HTMLReport.py(134)] - 
测试结束！
运行时间: 0:00:00.019940
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-14 17:28:46,735] [15604] [HTMLReport.py(94)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:28:46,737] [19600] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-14 17:28:46,738] [19600] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:28:46,739] [21996] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,740] [808] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,740] [21996] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:28:46,740] [8340] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,741] [808] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:28:46,742] [17788] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,743] [8340] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,744] [808] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[  ERROR] [2018-03-14 17:28:46,744] [19600] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,744] [17788] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:28:46,745] [8340] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,745] [808] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,745] [19600] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,746] [17788] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[WARNING] [2018-03-14 17:28:46,747] [21996] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,748] [17788] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,748] [21996] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,749] [17752] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,750] [17752] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:28:46,750] [22776] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,750] [17752] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,751] [22776] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,751] [17752] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,751] [22776] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,753] [21332] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,754] [21044] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:28:46,755] [21332] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:28:46,755] [21044] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,755] [21332] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,755] [21044] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,784] [15604] [HTMLReport.py(131)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-14 17:28:46,784] [15604] [HTMLReport.py(133)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:28:46,785] [15604] [HTMLReport.py(134)] - 
测试结束！
运行时间: 0:00:00.023278
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[  DEBUG] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(25)] - debug
[WARNING] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(26)] - warning
[   INFO] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(27)] - info
[  ERROR] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(28)] - error
[   INFO] [2018-03-14 17:28:53,404] [5984] [loggerTest.py(12)] - worker 0 info
[   INFO] [2018-03-14 17:28:53,404] [6220] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-14 17:28:53,404] [5984] [loggerTest.py(13)] - worker 0 调试
[  DEBUG] [2018-03-14 17:28:53,404] [6220] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-14 17:28:53,405] [5984] [loggerTest.py(14)] - worker 0 警告
[WARNING] [2018-03-14 17:28:53,405] [6220] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-14 17:28:53,405] [5984] [loggerTest.py(15)] - worker 0 错误
[  ERROR] [2018-03-14 17:28:53,405] [6220] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:30:34,767] [26004] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:30:34,768] [26004] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:30:34,769] [26004] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:30:34,769] [26004] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:30:34,770] [20452] [loggerTest.py(12)] - worker 0 info
[   INFO] [2018-03-18 12:30:34,770] [25400] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-18 12:30:34,771] [20452] [loggerTest.py(13)] - worker 0 调试
[  DEBUG] [2018-03-18 12:30:34,771] [25400] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-18 12:30:34,771] [20452] [loggerTest.py(14)] - worker 0 警告
[WARNING] [2018-03-18 12:30:34,772] [25400] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:30:34,772] [20452] [loggerTest.py(15)] - worker 0 错误
[  ERROR] [2018-03-18 12:30:34,772] [25400] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:33:14,003] [23468] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:33:14,004] [23468] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:33:14,004] [23468] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:33:14,004] [23468] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:33:14,007] [25328] [loggerTest.py(12)] - worker 0 info
[  DEBUG] [2018-03-18 12:33:14,007] [25328] [loggerTest.py(13)] - worker 0 调试
[   INFO] [2018-03-18 12:33:14,007] [25336] [loggerTest.py(12)] - worker 1 info
[WARNING] [2018-03-18 12:33:14,008] [25328] [loggerTest.py(14)] - worker 0 警告
[  DEBUG] [2018-03-18 12:33:14,008] [25336] [loggerTest.py(13)] - worker 1 调试
[  ERROR] [2018-03-18 12:33:14,008] [25328] [loggerTest.py(15)] - worker 0 错误
[WARNING] [2018-03-18 12:33:14,009] [25336] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:33:14,009] [25336] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:34:25,886] [14316] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:34:25,887] [14316] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:34:25,887] [14316] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:34:25,887] [14316] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:34:25,889] [20888] [loggerTest.py(12)] - worker 0 info
[  DEBUG] [2018-03-18 12:34:25,890] [20888] [loggerTest.py(13)] - worker 0 调试
[   INFO] [2018-03-18 12:34:25,891] [2252] [loggerTest.py(12)] - worker 1 info
[WARNING] [2018-03-18 12:34:25,892] [20888] [loggerTest.py(14)] - worker 0 警告
[  DEBUG] [2018-03-18 12:34:25,892] [2252] [loggerTest.py(13)] - worker 1 调试
[  ERROR] [2018-03-18 12:34:25,893] [20888] [loggerTest.py(15)] - worker 0 错误
[WARNING] [2018-03-18 12:34:25,893] [2252] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:34:25,893] [2252] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:34:36,165] [20132] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:34:36,167] [20132] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:34:36,167] [20132] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:34:36,168] [20132] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:34:36,181] [12648] [loggerTest.py(12)] - worker 0 info
[   INFO] [2018-03-18 12:34:36,184] [25944] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-18 12:34:36,185] [12648] [loggerTest.py(13)] - worker 0 调试
[  DEBUG] [2018-03-18 12:34:36,187] [25944] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-18 12:34:36,188] [12648] [loggerTest.py(14)] - worker 0 警告
[WARNING] [2018-03-18 12:34:36,190] [25944] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:34:36,192] [12648] [loggerTest.py(15)] - worker 0 错误
[  ERROR] [2018-03-18 12:34:36,193] [25944] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:34:42,969] [25792] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:34:42,974] [25792] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:34:42,976] [25792] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:34:42,977] [25792] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:34:42,990] [15772] [loggerTest.py(12)] - worker 0 info
[   INFO] [2018-03-18 12:34:42,993] [20340] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-18 12:34:42,995] [15772] [loggerTest.py(13)] - worker 0 调试
[  DEBUG] [2018-03-18 12:34:42,996] [20340] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-18 12:34:42,997] [15772] [loggerTest.py(14)] - worker 0 警告
[WARNING] [2018-03-18 12:34:42,998] [20340] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:34:42,999] [15772] [loggerTest.py(15)] - worker 0 错误
[  ERROR] [2018-03-18 12:34:43,002] [20340] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:34:49,054] [1188] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:34:49,057] [1188] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:34:49,058] [1188] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:34:49,059] [1188] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:34:49,072] [27000] [loggerTest.py(12)] - worker 0 info
[  DEBUG] [2018-03-18 12:34:49,074] [27000] [loggerTest.py(13)] - worker 0 调试
[WARNING] [2018-03-18 12:34:49,076] [27000] [loggerTest.py(14)] - worker 0 警告
[  ERROR] [2018-03-18 12:34:49,077] [27000] [loggerTest.py(15)] - worker 0 错误
[   INFO] [2018-03-18 12:34:49,079] [27000] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-18 12:34:49,080] [27000] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-18 12:34:49,083] [27000] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:34:49,083] [27000] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:34:54,338] [3400] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:34:54,340] [3400] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:34:54,340] [3400] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:34:54,341] [3400] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:34:54,356] [25272] [loggerTest.py(12)] - worker 0 info
[   INFO] [2018-03-18 12:34:54,360] [19492] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-18 12:34:54,363] [25272] [loggerTest.py(13)] - worker 0 调试
[  DEBUG] [2018-03-18 12:34:54,364] [19492] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-18 12:34:54,366] [25272] [loggerTest.py(14)] - worker 0 警告
[  ERROR] [2018-03-18 12:34:54,367] [25272] [loggerTest.py(15)] - worker 0 错误
[WARNING] [2018-03-18 12:34:54,368] [19492] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:34:54,370] [19492] [loggerTest.py(15)] - worker 1 错误
[  DEBUG] [2018-03-18 12:35:05,555] [21412] [loggerTest.py(25)] - debug
[WARNING] [2018-03-18 12:35:05,556] [21412] [loggerTest.py(26)] - warning
[   INFO] [2018-03-18 12:35:05,556] [21412] [loggerTest.py(27)] - info
[  ERROR] [2018-03-18 12:35:05,556] [21412] [loggerTest.py(28)] - error
[   INFO] [2018-03-18 12:35:05,562] [24868] [loggerTest.py(12)] - worker 0 info
[  DEBUG] [2018-03-18 12:35:05,566] [24868] [loggerTest.py(13)] - worker 0 调试
[   INFO] [2018-03-18 12:35:05,567] [26424] [loggerTest.py(12)] - worker 1 info
[WARNING] [2018-03-18 12:35:05,569] [24868] [loggerTest.py(14)] - worker 0 警告
[  DEBUG] [2018-03-18 12:35:05,570] [26424] [loggerTest.py(13)] - worker 1 调试
[  ERROR] [2018-03-18 12:35:05,572] [24868] [loggerTest.py(15)] - worker 0 错误
[WARNING] [2018-03-18 12:35:05,572] [26424] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-18 12:35:05,575] [26424] [loggerTest.py(15)] - worker 1 错误
[   INFO] [2018-03-18 12:35:17,436] [27236] [HTMLReport.py(94)] - 预计并发线程数：10
[   INFO] [2018-03-18 12:35:17,440] [15088] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,442] [26408] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-18 12:35:17,444] [15088] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-18 12:35:17,446] [24228] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,448] [26408] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-18 12:35:17,451] [22352] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,452] [24228] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-18 12:35:17,456] [19236] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,459] [22352] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-18 12:35:17,461] [15088] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,463] [24228] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,466] [19236] [HTMLReport_test.py(21)] - 测试split
[WARNING] [2018-03-18 12:35:17,467] [26408] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,468] [22352] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,469] [15088] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,470] [24228] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,471] [19236] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,472] [26408] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,476] [19236] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:35:17,480] [10688] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:35:17,483] [25256] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:35:17,484] [10688] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-18 12:35:17,486] [25256] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:35:17,487] [10688] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:35:17,488] [25256] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:35:17,488] [10688] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:35:17,492] [23692] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:35:17,496] [27048] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:35:17,499] [23692] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:35:17,501] [27048] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:35:17,501] [23692] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:35:17,502] [27048] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:36:31,201] [23248] [HTMLReport.py(94)] - 预计并发线程数：10
[   INFO] [2018-03-18 12:36:31,221] [24392] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,225] [3500] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-18 12:36:31,229] [24392] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-18 12:36:31,232] [14712] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,236] [14524] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,238] [3500] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-18 12:36:31,245] [14144] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,248] [14712] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-18 12:36:31,250] [14524] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-18 12:36:31,253] [24392] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,254] [14144] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-18 12:36:31,255] [14712] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,257] [14524] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[WARNING] [2018-03-18 12:36:31,259] [3500] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,260] [24392] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,262] [14144] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,264] [14712] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,266] [3500] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,267] [14144] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:36:31,281] [2772] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:36:31,286] [3384] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:36:31,289] [2772] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-18 12:36:31,291] [3384] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:36:31,293] [2772] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:36:31,294] [3384] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:36:31,295] [2772] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:36:31,302] [5316] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:36:31,308] [18856] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:36:31,311] [5316] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:36:31,315] [5316] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:36:31,317] [18856] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:36:31,320] [18856] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:53:47,739] [16832] [HTMLReport.py(97)] - 预计并发线程数：10
[   INFO] [2018-03-18 12:53:47,745] [20532] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,748] [25668] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-18 12:53:47,749] [20532] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-18 12:53:47,754] [23324] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,756] [25668] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-18 12:53:47,759] [16536] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,763] [23324] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-18 12:53:47,764] [15716] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,767] [16536] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-18 12:53:47,768] [20532] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,770] [23324] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[WARNING] [2018-03-18 12:53:47,771] [25668] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,773] [15716] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-18 12:53:47,773] [16536] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,773] [20532] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,774] [25668] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,775] [23324] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,777] [15716] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,781] [15716] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:53:47,788] [25164] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:53:47,794] [7596] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:53:47,798] [25164] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-18 12:53:47,800] [7596] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:53:47,802] [25164] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:53:47,804] [7596] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:53:47,805] [25164] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:53:47,811] [20704] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:53:47,815] [7844] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:53:47,820] [20704] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:53:47,825] [20704] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:53:47,827] [7844] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:53:47,830] [7844] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:54:00,619] [16832] [HTMLReport.py(134)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_upper (__main__.test_2th)	测试相等
Pass	test_bad_int (__main__.test_2th)	测试异常类型

[  ERROR] [2018-03-18 12:54:00,620] [16832] [HTMLReport.py(136)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-18 12:54:00,621] [16832] [HTMLReport.py(137)] - 
测试结束！
运行时间: 0:00:05.168284
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-18 12:57:00,318] [3628] [HTMLReport.py(97)] - 预计并发线程数：10
[   INFO] [2018-03-18 12:57:00,320] [25184] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-18 12:57:00,321] [25184] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-18 12:57:00,322] [15064] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,323] [15064] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-18 12:57:00,324] [26988] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,325] [26988] [HTMLReport_test.py(15)] - 测试isupper
[  ERROR] [2018-03-18 12:57:00,326] [25184] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,326] [26988] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,327] [25184] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,327] [8316] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,327] [26988] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[WARNING] [2018-03-18 12:57:00,327] [15064] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,328] [24320] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,328] [8316] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,329] [15064] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,329] [24320] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-18 12:57:00,330] [8316] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,330] [24320] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,331] [24320] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:57:00,331] [21144] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:57:00,332] [21144] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-18 12:57:00,332] [22084] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:57:00,333] [21144] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:57:00,333] [22084] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:57:00,334] [21144] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:57:00,334] [22084] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:57:00,335] [8996] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:00,336] [5204] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:57:00,337] [8996] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:57:00,337] [5204] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:00,338] [8996] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:00,338] [5204] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:00,374] [3628] [HTMLReport.py(134)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-18 12:57:00,374] [3628] [HTMLReport.py(136)] - 
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-18 12:57:00,375] [3628] [HTMLReport.py(137)] - 
测试结束！
运行时间: 0:00:00.023400
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-18 12:57:21,429] [27220] [HTMLReport.py(97)] - 预计并发线程数：10
[   INFO] [2018-03-18 12:57:21,433] [25668] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-18 12:57:21,435] [25668] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-18 12:57:21,437] [23324] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,442] [15716] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,443] [23324] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-18 12:57:21,445] [7596] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,448] [25164] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,449] [15716] [HTMLReport_test.py(15)] - 测试isupper
[  ERROR] [2018-03-18 12:57:21,451] [25668] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,453] [7596] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[WARNING] [2018-03-18 12:57:21,453] [23324] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,454] [25164] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-18 12:57:21,457] [25668] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,458] [15716] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,460] [7596] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,461] [23324] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,463] [25164] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,464] [15716] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,466] [25164] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:57:21,469] [20704] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:57:21,471] [20704] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-18 12:57:21,473] [7844] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:57:21,476] [20704] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:57:21,478] [7844] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:57:21,479] [20704] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:57:21,480] [7844] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:57:21,483] [5312] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:21,486] [9780] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:57:21,490] [5312] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:57:21,493] [9780] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:21,495] [5312] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:21,496] [9780] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:57:40,851] [27220] [HTMLReport.py(134)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-18 12:57:40,851] [27220] [HTMLReport.py(136)] - 
Error	test_error (__main__.test_1th)	测试错误
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-18 12:57:40,852] [27220] [HTMLReport.py(137)] - 
测试结束！
运行时间: 0:00:05.839789
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-18 12:59:12,821] [12340] [HTMLReport.py(97)] - 预计并发线程数：10
[   INFO] [2018-03-18 12:59:12,823] [5576] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-18 12:59:12,824] [5576] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-18 12:59:12,824] [26208] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,825] [26208] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-18 12:59:12,825] [19724] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,827] [19724] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-18 12:59:12,827] [380] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,829] [12776] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,829] [19724] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[  ERROR] [2018-03-18 12:59:12,829] [5576] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,830] [380] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,831] [12776] [HTMLReport_test.py(21)] - 测试split
[WARNING] [2018-03-18 12:59:12,831] [26208] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,831] [19724] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,831] [5576] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,831] [380] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,832] [12776] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,832] [26208] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,833] [12776] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-18 12:59:12,834] [13828] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:59:12,835] [13828] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-18 12:59:12,836] [24412] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:59:12,836] [13828] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:59:12,836] [24412] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:59:12,836] [13828] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-18 12:59:12,836] [24412] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-18 12:59:12,838] [24508] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:59:12,838] [27180] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:59:12,839] [24508] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-18 12:59:12,840] [27180] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:59:12,840] [24508] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:59:12,840] [27180] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-18 12:59:12,840] [12340] [HTMLReport.py(124)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-18 12:59:12,840] [12340] [HTMLReport.py(126)] - 
Error	test_error (__main__.test_1th)	测试错误
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-18 12:59:12,883] [12340] [HTMLReport.py(137)] - 
测试结束！
运行时间: 0:00:00.020587
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
