[   INFO] [2018-04-18 18:47:40,927] [20052] [HTMLReport.py(95)] - The number of concurrent threads is expected to be 5
[   INFO] [2018-04-18 18:47:40,928] [32292] [Result.py(44)] - Start Test: test_error (__main__.test_1th)
[  ERROR] [2018-04-18 18:47:40,929] [32292] [HTMLReport_test.py(35)] - 测试错误
[   INFO] [2018-04-18 18:47:40,929] [28956] [Result.py(44)] - Start Test: test_fail (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,929] [31276] [Result.py(44)] - Start Test: test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,929] [28956] [HTMLReport_test.py(45)] - 测试失败
[   INFO] [2018-04-18 18:47:40,930] [31276] [HTMLReport_test.py(20)] - 测试isupper
[   INFO] [2018-04-18 18:47:40,930] [31376] [Result.py(44)] - Start Test: test_skip (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,931] [27124] [Result.py(44)] - Start Test: test_split (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,931] [31276] [HTMLReport_test.py(21)] - 11111111111111111111111111111111111111111111111111111
[WARNING] [2018-04-18 18:47:40,932] [28956] [Result.py(126)] - Failure: test_fail (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 46, in test_fail
    self.assertEqual(1, 2, "相等")
AssertionError: 1 != 2 : 相等

[   INFO] [2018-04-18 18:47:40,932] [31376] [Result.py(77)] - Skip Test: test_skip (__main__.test_1th)
这是一个跳过的测试
[   INFO] [2018-04-18 18:47:40,933] [27124] [HTMLReport_test.py(27)] - 测试split
[   INFO] [2018-04-18 18:47:40,933] [31276] [Result.py(92)] - Pass Test: test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,933] [28956] [Result.py(55)] - Stop Test: test_fail (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,933] [31376] [Result.py(55)] - Stop Test: test_skip (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,934] [27124] [Result.py(92)] - Pass Test: test_split (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,934] [31276] [Result.py(55)] - Stop Test: test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,934] [28956] [Result.py(57)] - Duration: 0.003701383466672343
[   INFO] [2018-04-18 18:47:40,934] [31376] [Result.py(57)] - Duration: 0.0008473229688007247
[   INFO] [2018-04-18 18:47:40,934] [27124] [Result.py(55)] - Stop Test: test_split (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,934] [31276] [Result.py(57)] - Duration: 0.0039347869224119775
[   INFO] [2018-04-18 18:47:40,935] [27124] [Result.py(57)] - Duration: 0.0015813654330242323
[  ERROR] [2018-04-18 18:47:40,945] [32292] [Result.py(109)] - Error Test: test_error (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 41, in test_error
    raise ValueError
ValueError

[   INFO] [2018-04-18 18:47:40,945] [32292] [Result.py(55)] - Stop Test: test_error (__main__.test_1th)
[   INFO] [2018-04-18 18:47:40,946] [32292] [Result.py(57)] - Duration: 0.01674916883280786
[   INFO] [2018-04-18 18:47:40,946] [28336] [Result.py(44)] - Start Test: test_bad_int (__main__.test_2th)
[   INFO] [2018-04-18 18:47:40,946] [28336] [HTMLReport_test.py(58)] - 测试异常类型
[  ERROR] [2018-04-18 18:47:40,947] [28336] [Result.py(109)] - Error Test: test_bad_int (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 59, in test_bad_int
    self.assertRaises(ValueError, parse_int("1.5"), 'N/A')
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 11, in parse_int
    return int(s)
ValueError: invalid literal for int() with base 10: '1.5'

[   INFO] [2018-04-18 18:47:40,947] [52804] [Result.py(44)] - Start Test: test_upper (__main__.test_2th)
[   INFO] [2018-04-18 18:47:40,947] [28336] [Result.py(55)] - Stop Test: test_bad_int (__main__.test_2th)
[CRITICAL] [2018-04-18 18:47:40,947] [52804] [HTMLReport_test.py(63)] - 测试相等
[   INFO] [2018-04-18 18:47:40,947] [28336] [Result.py(57)] - Duration: 0.0007203575710531089
[WARNING] [2018-04-18 18:47:40,948] [52804] [Result.py(126)] - Failure: test_upper (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 64, in test_upper
    self.assertEqual('foo'.upper(), '00')
AssertionError: 'FOO' != '00'
- FOO
+ 00


[   INFO] [2018-04-18 18:47:40,948] [52804] [Result.py(55)] - Stop Test: test_upper (__main__.test_2th)
[   INFO] [2018-04-18 18:47:40,948] [52804] [Result.py(57)] - Duration: 0.0008420010659011233
[   INFO] [2018-04-18 18:47:40,948] [28996] [Result.py(44)] - Start Test: test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 18:47:40,949] [16340] [Result.py(44)] - Start Test: test_True (__main__.test_第三个测试)
[WARNING] [2018-04-18 18:47:40,949] [28996] [Result.py(126)] - Failure: test_False (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 83, in test_False
    self.assertFalse(True, self.a)
AssertionError: True is not false : 2

[WARNING] [2018-04-18 18:47:40,949] [16340] [Result.py(126)] - Failure: test_True (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 78, in test_True
    self.assertTrue(False, self.a)
AssertionError: False is not true : 3

[   INFO] [2018-04-18 18:47:40,950] [28996] [Result.py(55)] - Stop Test: test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 18:47:40,950] [16340] [Result.py(55)] - Stop Test: test_True (__main__.test_第三个测试)
[   INFO] [2018-04-18 18:47:40,950] [28996] [Result.py(57)] - Duration: 0.0006504125615154933
[   INFO] [2018-04-18 18:47:40,950] [16340] [Result.py(57)] - Duration: 0.0006477516100656944
[   INFO] [2018-04-18 18:47:40,950] [20052] [HTMLReport.py(123)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split

[  ERROR] [2018-04-18 18:47:40,951] [20052] [HTMLReport.py(125)] - 
Fail	test_fail (__main__.test_1th)	测试失败
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Error	test_bad_int (__main__.test_2th)	测试异常类型
Fail	test_upper (__main__.test_2th)	测试相等
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-04-18 18:47:40,969] [20052] [HTMLReport.py(143)] - 
EOT！
Ran 9 tests in 0:00:00.022958

PASS：2
Failures：4
Skipped：1
Errors：2
