[   INFO] [2018-04-18 10:50:01,677] [25956] [HTMLReport.py(95)] - The number of concurrent threads is expected to be 5
[   INFO] [2018-04-18 10:50:01,678] [54784] [Result.py(45)] - Start Test:	test_error (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,679] [59508] [Result.py(45)] - Start Test:	test_fail (__main__.test_1th)
[  ERROR] [2018-04-18 10:50:01,679] [54784] [HTMLReport_test.py(35)] - 测试错误
[   INFO] [2018-04-18 10:50:01,679] [58524] [Result.py(45)] - Start Test:	test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,680] [59508] [HTMLReport_test.py(45)] - 测试失败
[   INFO] [2018-04-18 10:50:01,680] [58736] [Result.py(45)] - Start Test:	test_skip (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,681] [58524] [HTMLReport_test.py(20)] - 测试isupper
[   INFO] [2018-04-18 10:50:01,681] [60316] [Result.py(45)] - Start Test:	test_split (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,681] [58736] [Result.py(78)] - Skip Test:	test_skip (__main__.test_1th)
这是一个跳过的测试
[   INFO] [2018-04-18 10:50:01,682] [58524] [HTMLReport_test.py(21)] - 11111111111111111111111111111111111111111111111111111
[   INFO] [2018-04-18 10:50:01,682] [60316] [HTMLReport_test.py(27)] - 测试split
[WARNING] [2018-04-18 10:50:01,683] [59508] [Result.py(127)] - Failure:	test_fail (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 46, in test_fail
    self.assertEqual(1, 2, "相等")
AssertionError: 1 != 2 : 相等

[   INFO] [2018-04-18 10:50:01,683] [58736] [Result.py(56)] - Stop Test:	test_skip (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,683] [58524] [Result.py(93)] - Pass Test:	test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,684] [60316] [Result.py(93)] - Pass Test:	test_split (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,684] [59508] [Result.py(56)] - Stop Test:	test_fail (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,684] [58736] [Result.py(58)] - Duration:	0.0015068587924298212
[   INFO] [2018-04-18 10:50:01,684] [58524] [Result.py(56)] - Stop Test:	test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,685] [60316] [Result.py(56)] - Stop Test:	test_split (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,685] [59508] [Result.py(58)] - Duration:	0.004461655309472455
[   INFO] [2018-04-18 10:50:01,685] [58524] [Result.py(58)] - Duration:	0.0039560745340103814
[   INFO] [2018-04-18 10:50:01,685] [60316] [Result.py(58)] - Duration:	0.0022667504993085326
[  ERROR] [2018-04-18 10:50:01,693] [54784] [Result.py(110)] - Error Test:	test_error (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 41, in test_error
    raise ValueError
ValueError

[   INFO] [2018-04-18 10:50:01,694] [54784] [Result.py(56)] - Stop Test:	test_error (__main__.test_1th)
[   INFO] [2018-04-18 10:50:01,694] [54784] [Result.py(58)] - Duration:	0.01492223559455919
[   INFO] [2018-04-18 10:50:01,694] [58576] [Result.py(45)] - Start Test:	test_bad_int (__main__.test_2th)
[   INFO] [2018-04-18 10:50:01,695] [55604] [Result.py(45)] - Start Test:	test_upper (__main__.test_2th)
[   INFO] [2018-04-18 10:50:01,695] [58576] [HTMLReport_test.py(58)] - 测试异常类型
[CRITICAL] [2018-04-18 10:50:01,695] [55604] [HTMLReport_test.py(63)] - 测试相等
[  ERROR] [2018-04-18 10:50:01,696] [58576] [Result.py(110)] - Error Test:	test_bad_int (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 59, in test_bad_int
    self.assertRaises(ValueError, parse_int("1.5"), 'N/A')
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 11, in parse_int
    return int(s)
ValueError: invalid literal for int() with base 10: '1.5'

[   INFO] [2018-04-18 10:50:01,696] [58576] [Result.py(56)] - Stop Test:	test_bad_int (__main__.test_2th)
[WARNING] [2018-04-18 10:50:01,696] [55604] [Result.py(127)] - Failure:	test_upper (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 64, in test_upper
    self.assertEqual('foo'.upper(), '00')
AssertionError: 'FOO' != '00'
- FOO
+ 00


[   INFO] [2018-04-18 10:50:01,696] [58576] [Result.py(58)] - Duration:	0.0010008978810463476
[   INFO] [2018-04-18 10:50:01,696] [55604] [Result.py(56)] - Stop Test:	test_upper (__main__.test_2th)
[   INFO] [2018-04-18 10:50:01,696] [55604] [Result.py(58)] - Duration:	0.0011077160749597623
[   INFO] [2018-04-18 10:50:01,697] [52580] [Result.py(45)] - Start Test:	test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 10:50:01,697] [51192] [Result.py(45)] - Start Test:	test_True (__main__.test_第三个测试)
[WARNING] [2018-04-18 10:50:01,698] [52580] [Result.py(127)] - Failure:	test_False (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 83, in test_False
    self.assertFalse(True, self.a)
AssertionError: True is not false : 2

[   INFO] [2018-04-18 10:50:01,698] [52580] [Result.py(56)] - Stop Test:	test_False (__main__.test_第三个测试)
[WARNING] [2018-04-18 10:50:01,698] [51192] [Result.py(127)] - Failure:	test_True (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 78, in test_True
    self.assertTrue(False, self.a)
AssertionError: False is not true : 3

[   INFO] [2018-04-18 10:50:01,698] [52580] [Result.py(58)] - Duration:	0.000640909163480495
[   INFO] [2018-04-18 10:50:01,699] [51192] [Result.py(56)] - Stop Test:	test_True (__main__.test_第三个测试)
[   INFO] [2018-04-18 10:50:01,699] [51192] [Result.py(58)] - Duration:	0.0008484633765649258
[   INFO] [2018-04-18 10:50:01,699] [25956] [HTMLReport.py(123)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split

[  ERROR] [2018-04-18 10:50:01,700] [25956] [HTMLReport.py(125)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Error	test_error (__main__.test_1th)	测试错误
Error	test_bad_int (__main__.test_2th)	测试异常类型
Fail	test_upper (__main__.test_2th)	测试相等
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-04-18 10:50:01,721] [25956] [HTMLReport.py(143)] - 
EOT！
Ran 9 tests in 0:00:00.021960

PASS：2
Failures：4
Skipped：1
Errors：2
