[   INFO] [2018-04-18 12:33:07,298] [23900] [HTMLReport.py(95)] - The number of concurrent threads is expected to be 5
[   INFO] [2018-04-18 12:33:07,299] [25156] [Result.py(45)] - Start Test:	test_error (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,299] [24860] [Result.py(45)] - Start Test:	test_fail (__main__.test_1th)
[  ERROR] [2018-04-18 12:33:07,300] [25156] [HTMLReport_test.py(35)] - 测试错误
[   INFO] [2018-04-18 12:33:07,300] [22524] [Result.py(45)] - Start Test:	test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,300] [22860] [Result.py(45)] - Start Test:	test_skip (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,300] [24860] [HTMLReport_test.py(45)] - 测试失败
[   INFO] [2018-04-18 12:33:07,301] [2740] [Result.py(45)] - Start Test:	test_split (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,301] [22524] [HTMLReport_test.py(20)] - 测试isupper
[   INFO] [2018-04-18 12:33:07,301] [22860] [Result.py(78)] - Skip Test:	test_skip (__main__.test_1th)
这是一个跳过的测试
[WARNING] [2018-04-18 12:33:07,302] [24860] [Result.py(127)] - Failure:	test_fail (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 46, in test_fail
    self.assertEqual(1, 2, "相等")
AssertionError: 1 != 2 : 相等

[   INFO] [2018-04-18 12:33:07,303] [2740] [HTMLReport_test.py(27)] - 测试split
[   INFO] [2018-04-18 12:33:07,303] [22524] [HTMLReport_test.py(21)] - 11111111111111111111111111111111111111111111111111111
[   INFO] [2018-04-18 12:33:07,303] [22860] [Result.py(56)] - Stop Test:	test_skip (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,303] [24860] [Result.py(56)] - Stop Test:	test_fail (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,304] [2740] [Result.py(93)] - Pass Test:	test_split (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,304] [22524] [Result.py(93)] - Pass Test:	test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,304] [22860] [Result.py(58)] - Duration:	0.0019432548301970855
[   INFO] [2018-04-18 12:33:07,304] [24860] [Result.py(58)] - Duration:	0.002959738284020834
[   INFO] [2018-04-18 12:33:07,305] [2740] [Result.py(56)] - Stop Test:	test_split (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,305] [22524] [Result.py(56)] - Stop Test:	test_isupper (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,305] [2740] [Result.py(58)] - Duration:	0.0018672276459170746
[   INFO] [2018-04-18 12:33:07,306] [22524] [Result.py(58)] - Duration:	0.0038032598936075584
[  ERROR] [2018-04-18 12:33:07,312] [25156] [Result.py(110)] - Error Test:	test_error (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 41, in test_error
    raise ValueError
ValueError

[   INFO] [2018-04-18 12:33:07,312] [25156] [Result.py(56)] - Stop Test:	test_error (__main__.test_1th)
[   INFO] [2018-04-18 12:33:07,312] [25156] [Result.py(58)] - Duration:	0.012711365075696465
[   INFO] [2018-04-18 12:33:07,313] [23044] [Result.py(45)] - Start Test:	test_bad_int (__main__.test_2th)
[   INFO] [2018-04-18 12:33:07,313] [9348] [Result.py(45)] - Start Test:	test_upper (__main__.test_2th)
[   INFO] [2018-04-18 12:33:07,314] [23044] [HTMLReport_test.py(58)] - 测试异常类型
[CRITICAL] [2018-04-18 12:33:07,314] [9348] [HTMLReport_test.py(63)] - 测试相等
[  ERROR] [2018-04-18 12:33:07,314] [23044] [Result.py(110)] - Error Test:	test_bad_int (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 59, in test_bad_int
    self.assertRaises(ValueError, parse_int("1.5"), 'N/A')
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 11, in parse_int
    return int(s)
ValueError: invalid literal for int() with base 10: '1.5'

[   INFO] [2018-04-18 12:33:07,314] [23044] [Result.py(56)] - Stop Test:	test_bad_int (__main__.test_2th)
[   INFO] [2018-04-18 12:33:07,315] [23044] [Result.py(58)] - Duration:	0.000976949317998143
[WARNING] [2018-04-18 12:33:07,314] [9348] [Result.py(127)] - Failure:	test_upper (__main__.test_2th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 64, in test_upper
    self.assertEqual('foo'.upper(), '00')
AssertionError: 'FOO' != '00'
- FOO
+ 00


[   INFO] [2018-04-18 12:33:07,315] [9348] [Result.py(56)] - Stop Test:	test_upper (__main__.test_2th)
[   INFO] [2018-04-18 12:33:07,315] [9348] [Result.py(58)] - Duration:	0.0013399791229351966
[   INFO] [2018-04-18 12:33:07,316] [25240] [Result.py(45)] - Start Test:	test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 12:33:07,316] [18992] [Result.py(45)] - Start Test:	test_True (__main__.test_第三个测试)
[WARNING] [2018-04-18 12:33:07,316] [25240] [Result.py(127)] - Failure:	test_False (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 83, in test_False
    self.assertFalse(True, self.a)
AssertionError: True is not false : 2

[   INFO] [2018-04-18 12:33:07,317] [25240] [Result.py(56)] - Stop Test:	test_False (__main__.test_第三个测试)
[   INFO] [2018-04-18 12:33:07,317] [25240] [Result.py(58)] - Duration:	0.00045084120278046647
[WARNING] [2018-04-18 12:33:07,317] [18992] [Result.py(127)] - Failure:	test_True (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 78, in test_True
    self.assertTrue(False, self.a)
AssertionError: False is not true : 3

[   INFO] [2018-04-18 12:33:07,317] [18992] [Result.py(56)] - Stop Test:	test_True (__main__.test_第三个测试)
[   INFO] [2018-04-18 12:33:07,317] [18992] [Result.py(58)] - Duration:	0.0007131349885465058
[   INFO] [2018-04-18 12:33:07,317] [23900] [HTMLReport.py(123)] - 
Pass	test_split (__main__.test_1th)	测试split
Pass	test_isupper (__main__.test_1th)	测试isupper

[  ERROR] [2018-04-18 12:33:07,317] [23900] [HTMLReport.py(125)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Error	test_error (__main__.test_1th)	测试错误
Error	test_bad_int (__main__.test_2th)	测试异常类型
Fail	test_upper (__main__.test_2th)	测试相等
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-04-18 12:33:07,337] [23900] [HTMLReport.py(143)] - 
EOT！
Ran 9 tests in 0:00:00.019463

PASS：2
Failures：4
Skipped：1
Errors：2
