[   INFO] [2018-03-23 16:15:53,494] [17936] [HTMLReport.py(100)] - 预计并发线程数：10
[   INFO] [2018-03-23 16:15:53,495] [11408] [Result.py(43)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-23 16:15:53,495] [11408] [HTMLReport_test.py(30)] - 测试错误
[   INFO] [2018-03-23 16:15:53,496] [17076] [Result.py(43)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,496] [17728] [Result.py(43)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,496] [17076] [HTMLReport_test.py(40)] - 测试失败
[   INFO] [2018-03-23 16:15:53,496] [10644] [Result.py(43)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,497] [17728] [HTMLReport_test.py(16)] - 测试isupper
[   INFO] [2018-03-23 16:15:53,498] [16552] [Result.py(43)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,499] [10644] [Result.py(72)] - 跳过测试：	test_skip (__main__.test_1th)
这是一个跳过的测试
[WARNING] [2018-03-23 16:15:53,499] [17076] [Result.py(120)] - 测试未通过：	test_fail (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 41, in test_fail
    self.assertEqual(1, 2, "相等")
AssertionError: 1 != 2 : 相等

[   INFO] [2018-03-23 16:15:53,500] [17728] [Result.py(87)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,501] [16552] [HTMLReport_test.py(22)] - 测试split
[   INFO] [2018-03-23 16:15:53,501] [10644] [Result.py(53)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,501] [17076] [Result.py(53)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,501] [17728] [Result.py(53)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,501] [16552] [Result.py(87)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,502] [16552] [Result.py(53)] - 测试结束：test_split (__main__.test_1th)
[  ERROR] [2018-03-23 16:15:53,538] [11408] [Result.py(103)] - 测试产生错误：	test_error (__main__.test_1th)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 36, in test_error
    raise ValueError
ValueError

[   INFO] [2018-03-23 16:15:53,538] [11408] [Result.py(53)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-23 16:15:53,539] [6228] [Result.py(43)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-23 16:15:53,539] [6228] [HTMLReport_test.py(53)] - 测试异常类型
[   INFO] [2018-03-23 16:15:53,539] [9704] [Result.py(43)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-23 16:15:53,540] [6228] [Result.py(87)] - 测试执行通过：test_bad_int (__main__.test_2th)
[CRITICAL] [2018-03-23 16:15:53,540] [9704] [HTMLReport_test.py(58)] - 测试执行
[   INFO] [2018-03-23 16:15:53,540] [6228] [Result.py(53)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-23 16:15:53,541] [9704] [Result.py(87)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-23 16:15:53,541] [9704] [Result.py(53)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-23 16:15:53,544] [10196] [Result.py(43)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-23 16:15:53,544] [17376] [Result.py(43)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-23 16:15:53,545] [10196] [Result.py(120)] - 测试未通过：	test_False (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 78, in test_False
    self.assertFalse(True, self.a)
AssertionError: True is not false : 2

[   INFO] [2018-03-23 16:15:53,545] [10196] [Result.py(53)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-23 16:15:53,546] [17376] [Result.py(120)] - 测试未通过：	test_True (__main__.test_第三个测试)
Traceback (most recent call last):
  File "C:/Users/liush/Documents/GitHub/HTMLReport/tests/HTMLReport_test.py", line 73, in test_True
    self.assertTrue(False, self.a)
AssertionError: False is not true : 3

[   INFO] [2018-03-23 16:15:53,546] [17376] [Result.py(53)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-23 16:15:53,546] [17936] [HTMLReport.py(127)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-23 16:15:53,547] [17936] [HTMLReport.py(129)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Error	test_error (__main__.test_1th)	测试错误
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-23 16:15:53,572] [17936] [HTMLReport.py(140)] - 
测试结束！
运行时间: 0:00:00.059668
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
